"""Initial schema

Revision ID: 2f44ce3f6db2
Revises: 
Create Date: 2026-10-08 14:54:56.643168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f44ce3f6db2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ecs_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('document', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ecs_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecs_clients_name'), ['name'], unique=False)

    op.create_table('ecs_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("role IN ('admin','equipe')", name='ecs_user_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ecs_vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=10), nullable=False),
    sa.Column('fleet', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('year', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['ecs_clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate')
    )
    op.create_table('ecs_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('delivered_date', sa.Date(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('responsible', sa.String(length=120), nullable=False),
    sa.Column('problem', sa.Text(), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.CheckConstraint('due_date >= entry_date', name='ecs_order_dates'),
    sa.CheckConstraint('mileage >= 0 AND discount >= 0', name='ecs_order_nonnegative'),
    sa.ForeignKeyConstraint(['client_id'], ['ecs_clients.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['ecs_vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('ecs_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecs_orders_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecs_orders_entry_date'), ['entry_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecs_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ecs_orders_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('ecs_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.CheckConstraint("result IN ('pendente','ok','avaria','na')", name='ecs_check_result'),
    sa.CheckConstraint("stage IN ('entrada','saida')", name='ecs_check_stage'),
    sa.ForeignKeyConstraint(['order_id'], ['ecs_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ecs_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecs_checks_order_id'), ['order_id'], unique=False)

    op.create_table('ecs_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['ecs_orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ecs_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ecs_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecs_events_order_id'), ['order_id'], unique=False)

    op.create_table('ecs_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=15), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('responsible', sa.String(length=120), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.CheckConstraint("kind IN ('servico','peca')", name='ecs_item_kind'),
    sa.CheckConstraint('quantity > 0 AND unit_price >= 0', name='ecs_item_nonnegative'),
    sa.ForeignKeyConstraint(['order_id'], ['ecs_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ecs_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecs_items_order_id'), ['order_id'], unique=False)

    op.create_table('ecs_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=False),
    sa.Column('stage', sa.String(length=10), nullable=False),
    sa.Column('caption', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['ecs_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ecs_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ecs_photos_order_id'), ['order_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecs_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecs_photos_order_id'))

    op.drop_table('ecs_photos')
    with op.batch_alter_table('ecs_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecs_items_order_id'))

    op.drop_table('ecs_items')
    with op.batch_alter_table('ecs_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecs_events_order_id'))

    op.drop_table('ecs_events')
    with op.batch_alter_table('ecs_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecs_checks_order_id'))

    op.drop_table('ecs_checks')
    with op.batch_alter_table('ecs_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecs_orders_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_ecs_orders_status'))
        batch_op.drop_index(batch_op.f('ix_ecs_orders_entry_date'))
        batch_op.drop_index(batch_op.f('ix_ecs_orders_due_date'))

    op.drop_table('ecs_orders')
    op.drop_table('ecs_vehicles')
    op.drop_table('ecs_users')
    with op.batch_alter_table('ecs_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ecs_clients_name'))

    op.drop_table('ecs_clients')
    # ### end Alembic commands ###
